### ISSUE TITLE
CITATION file

### ISSUE THREAD

**Issue by drvinceknight** [debsankha/flownetpy#1]
I am currently part of a group of people writing a paper on testing for research software, as your code uses property based test (hypothesis) I would like to reference it. Have you thought about adding a citation file?

Details here: http://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files

Example here: https://github.com/dib-lab/khmer/blob/master/CITATION

Thanks!

**Comment by debsankha** [comment]
Hi @drvinceknight t:

I have integrated `flownetpy` with [zenedo](https://zenodo.org/record/48233). There one can generate 
citations in one's preferred format. 

Does this take care of of your use case? 

And of course, thanks for referencing my work. May I ask, what is the aim of your project? 
If you are interested, I could also point you to software projects of my colleagues. 
Feel free to email me, the address is here:
http://www.nld.ds.mpg.de/people/manik

**Comment by drvinceknight** [comment]
Sorry for the late reply @debsankha!

Great that you've integrated with zenodo. A [CITATION file](http://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files) mainly aims to give instructions as to how to cite. So for example you could write the zenodo url in there and instruct to cite according to that?

Basically, the idea of a CITATION file is to standardise instructions :)

> And of course, thanks for referencing my work. May I ask, what is the aim of your project? 

We're just writing a paper about testing for research software (this was a hackathon project at http://www.software.ac.uk/cw16). I'm writing a section on property based tests (hypothesis) and I want to cite software that makes use of it.

**Comment by debsankha** [comment]
No problem!

Point taken, I have added a CITATION file here:
https://github.com/debsankha/flownetpy/blob/master/CITATION.md
